//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rtt.ClientManager.RttServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/Rtt.ClientManager.WS")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RttServiceReference.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateDatabase", ReplyAction="http://tempuri.org/IService1/CreateDatabaseResponse")]
        void CreateDatabase();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateDatabase", ReplyAction="http://tempuri.org/IService1/CreateDatabaseResponse")]
        System.Threading.Tasks.Task CreateDatabaseAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        Rtt.ClientManager.RttServiceReference.CompositeType GetDataUsingDataContract(Rtt.ClientManager.RttServiceReference.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<Rtt.ClientManager.RttServiceReference.CompositeType> GetDataUsingDataContractAsync(Rtt.ClientManager.RttServiceReference.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteClient", ReplyAction="http://tempuri.org/IService1/DeleteClientResponse")]
        void DeleteClient(Rtt.ClientManager.Shared.Client client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteClient", ReplyAction="http://tempuri.org/IService1/DeleteClientResponse")]
        System.Threading.Tasks.Task DeleteClientAsync(Rtt.ClientManager.Shared.Client client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateClient", ReplyAction="http://tempuri.org/IService1/UpdateClientResponse")]
        void UpdateClient(Rtt.ClientManager.Shared.Client client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateClient", ReplyAction="http://tempuri.org/IService1/UpdateClientResponse")]
        System.Threading.Tasks.Task UpdateClientAsync(Rtt.ClientManager.Shared.Client client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllClients", ReplyAction="http://tempuri.org/IService1/GetAllClientsResponse")]
        Rtt.ClientManager.Shared.Client[] GetAllClients();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllClients", ReplyAction="http://tempuri.org/IService1/GetAllClientsResponse")]
        System.Threading.Tasks.Task<Rtt.ClientManager.Shared.Client[]> GetAllClientsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateClient", ReplyAction="http://tempuri.org/IService1/CreateClientResponse")]
        Rtt.ClientManager.Shared.Client CreateClient([System.ServiceModel.MessageParameterAttribute(Name="createClient")] Rtt.ClientManager.Shared.Client createClient1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateClient", ReplyAction="http://tempuri.org/IService1/CreateClientResponse")]
        System.Threading.Tasks.Task<Rtt.ClientManager.Shared.Client> CreateClientAsync(Rtt.ClientManager.Shared.Client createClient);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Upsert", ReplyAction="http://tempuri.org/IService1/UpsertResponse")]
        Rtt.ClientManager.Shared.Client Upsert(Rtt.ClientManager.Shared.Client updClient);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Upsert", ReplyAction="http://tempuri.org/IService1/UpsertResponse")]
        System.Threading.Tasks.Task<Rtt.ClientManager.Shared.Client> UpsertAsync(Rtt.ClientManager.Shared.Client updClient);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Rtt.ClientManager.RttServiceReference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Rtt.ClientManager.RttServiceReference.IService1>, Rtt.ClientManager.RttServiceReference.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public void CreateDatabase() {
            base.Channel.CreateDatabase();
        }
        
        public System.Threading.Tasks.Task CreateDatabaseAsync() {
            return base.Channel.CreateDatabaseAsync();
        }
        
        public Rtt.ClientManager.RttServiceReference.CompositeType GetDataUsingDataContract(Rtt.ClientManager.RttServiceReference.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<Rtt.ClientManager.RttServiceReference.CompositeType> GetDataUsingDataContractAsync(Rtt.ClientManager.RttServiceReference.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public void DeleteClient(Rtt.ClientManager.Shared.Client client) {
            base.Channel.DeleteClient(client);
        }
        
        public System.Threading.Tasks.Task DeleteClientAsync(Rtt.ClientManager.Shared.Client client) {
            return base.Channel.DeleteClientAsync(client);
        }
        
        public void UpdateClient(Rtt.ClientManager.Shared.Client client) {
            base.Channel.UpdateClient(client);
        }
        
        public System.Threading.Tasks.Task UpdateClientAsync(Rtt.ClientManager.Shared.Client client) {
            return base.Channel.UpdateClientAsync(client);
        }
        
        public Rtt.ClientManager.Shared.Client[] GetAllClients() {
            return base.Channel.GetAllClients();
        }
        
        public System.Threading.Tasks.Task<Rtt.ClientManager.Shared.Client[]> GetAllClientsAsync() {
            return base.Channel.GetAllClientsAsync();
        }
        
        public Rtt.ClientManager.Shared.Client CreateClient(Rtt.ClientManager.Shared.Client createClient1) {
            return base.Channel.CreateClient(createClient1);
        }
        
        public System.Threading.Tasks.Task<Rtt.ClientManager.Shared.Client> CreateClientAsync(Rtt.ClientManager.Shared.Client createClient) {
            return base.Channel.CreateClientAsync(createClient);
        }
        
        public Rtt.ClientManager.Shared.Client Upsert(Rtt.ClientManager.Shared.Client updClient) {
            return base.Channel.Upsert(updClient);
        }
        
        public System.Threading.Tasks.Task<Rtt.ClientManager.Shared.Client> UpsertAsync(Rtt.ClientManager.Shared.Client updClient) {
            return base.Channel.UpsertAsync(updClient);
        }
    }
}
